# Generated by Django 2.1.dev20180303195639 on 2018-03-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=60, verbose_name='Lead name')),
                ('email_text', models.EmailField(max_length=254, verbose_name='Lead Email')),
            ],
        ),
    ]
